name: Build linux kernel for zover-os

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt install bison flex libelf-dev libssl-dev -y
    - name: download source
      run: wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.67.tar.xz
    - name: unpack
      run: tar xvf linux-5.15.67.tar.xz
    - name: download config
      working-directory: ./linux-5.15.67
      run: wget -O .config https://github.com/zover-os/configs/raw/main/linux-5.15.67.config
    - name: apply patches
      working-directory: ./linux-5.15.67
      run: for i in ../patches/*.patch; do patch -p1 -i $i; done
    - name: build kernel
      working-directory: ./linux-5.15.67
      run: make -j$(nproc --all)
    - name: install modules to dir
      working-directory: ./linux-5.15.67
      run: |
        mkdir modules
        make INSTALL_MOD_PATH=modules modules_install
        zip -r modules.zip modules
    - uses: actions/upload-artifact@v3
      with:
        name: kernel
        path: |
          ./linux-5.15.67/arch/x86/boot/bzImage
          ./linux-5.15.67/modules.zip
